server.port: 8888

spring.datasource:
  url: 'jdbc:postgresql://127.0.0.1:5432/postgres'
  username: 'postgres'
  password: 'admin1234'
  
spring.jpa:
  show-sql: true
  ## Hibernate Properties
  properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  # Hibernate ddl auto (create, create-drop, validate, update)
  hibernate.ddl-auto: update # update

spring.sql.init:
  # schema-locations: classpath:ddl/DDL_DROPS.sql, classpath:ddl/DDL_TUSERS.sql, classpath:ddl/DDL_TPOSTS.sql
  mode: always # always